In [12]:
import pandas as pd
df = pd.read_csv("SuperStore_Sales_Clean.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode
0,4918,CA-2019-160304,1/1/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.27,0,Online
1,4919,CA-2019-160304,1/2/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.27,0,Online
2,4920,CA-2019-160304,1/2/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,East,TEC-PH-10000455,Technology,Phones,GE 30522EE2,231.98,2,67.27,0,Cards
3,3074,CA-2019-125206,1/3/2019,1/5/2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,West,OFF-ST-10003692,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.62,0,Online
4,8604,US-2019-116365,1/3/2019,1/8/2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Central,TEC-AC-10002217,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.26,0,Online

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         5901 non-null   int64
 1   Order ID       5901 non-null   object
 2   Order Date     5901 non-null   object
 3   Ship Date      5901 non-null   object
 4   Ship Mode      5901 non-null   object
 5   Customer ID    5901 non-null   object
 6   Customer Name  5901 non-null   object
 7   Segment        5901 non-null   object
 8   Country        5901 non-null   object
 9   City           5901 non-null   object
 10  State          5901 non-null   object
 11  Region         5901 non-null   object
 12  Product ID     5901 non-null   object
 13  Category       5901 non-null   object
 14  Sub-Category   5901 non-null   object
 15  Product Name   5901 non-null   object
 16  Sales          5901 non-null   float64
 17  Quantity       5901 non-null   int64
 18  Profit         5901 non-null   float64
 19  Returns        5901 non-null   int64
 20  Payment Mode   5901 non-null   object
dtypes: float64(2), int64(3), object(16)
memory usage: 968.3+ KB

In [14]:
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce', dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], errors='coerce', dayfirst=True)

In [15]:
df = df.dropna(subset=['Order Date','Ship Date'])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1685 entries, 0 to 5677
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         1685 non-null   int64
 1   Order ID       1685 non-null   object
 2   Order Date     1685 non-null   datetime64[ns]
 3   Ship Date      1685 non-null   datetime64[ns]
 4   Ship Mode      1685 non-null   object
 5   Customer ID    1685 non-null   object
 6   Customer Name  1685 non-null   object
 7   Segment        1685 non-null   object
 8   Country        1685 non-null   object
 9   City           1685 non-null   object
 10  State          1685 non-null   object
 11  Region         1685 non-null   object
 12  Product ID     1685 non-null   object
 13  Category       1685 non-null   object
 14  Sub-Category   1685 non-null   object
 15  Product Name   1685 non-null   object
 16  Sales          1685 non-null   float64
 17  Quantity       1685 non-null   int64
 18  Profit         1685 non-null   float64
 19  Returns        1685 non-null   int64
 20  Payment Mode   1685 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(3), object(14)
memory usage: 289.6+ KB

In [17]:
df.sort_values(by="Profit").head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode
5037,684,US-2020-168116,2020-04-11,2020-04-11,Same Day,GT-14635,Grant Thornton,Corporate,United States,Burlington,...,South,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,3009.98,4,-3839.99,0,Online
383,1200,CA-2019-130946,2019-08-04,2019-12-04,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,1088.79,4,-1850.95,0,Online
4702,5321,US-2020-162558,2020-02-10,2020-05-10,First Class,Dp-13240,Dean percer,Home Office,United States,Knoxville,...,South,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,2335.12,7,-1002.78,0,Online
1700,7642,US-2019-157490,2019-06-10,2019-07-10,First Class,LB-16795,Laurel Beltran,Home Office,United States,Pueblo,...,West,TEC-MA-10001695,Technology,Machines,Zebra GK420t Direct Thermal/Thermal Transfer P...,703.71,6,-938.28,0,Online
189,5199,CA-2019-103982,2019-03-03,2019-08-03,Standard Class,AA-10315,Alex Avila,Consumer,United States,Round Rock,...,Central,OFF-SU-10000151,Office Supplies,Supplies,High Speed Automatic Electric Letter Opener,3930.07,3,-786.01,0,Online
5480,1996,US-2020-147221,2020-02-12,2020-04-12,Second Class,JS-16030,Joy Smith,Consumer,United States,Houston,...,Central,OFF-AP-10002534,Office Supplies,Appliances,3.6 Cubic Foot Counter Height Office Refrigerator,334.62,5,-766.01,0,COD
1353,870,CA-2019-158099,2019-03-09,2019-05-09,First Class,PK-18910,Paul Knutson,Home Office,United States,Philadelphia,...,East,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,1141.47,5,-760.98,0,Cards
5483,4498,CA-2020-155075,2020-02-12,2020-09-12,Standard Class,GW-14605,Giulietta Weimer,Consumer,United States,Philadelphia,...,East,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,155.18,4,-462.86,0,COD
3293,8236,CA-2020-102204,2020-01-05,2020-06-05,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Jacksonville,...,South,FUR-TA-10001889,Furniture,Tables,Bush Advantage Collection Racetrack Conference...,952.26,4,-458.15,0,COD
2762,6567,CA-2020-131282,2020-05-02,2020-08-02,Second Class,CB-12025,Cassandra Brandow,Consumer,United States,Waco,...,Central,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,285.99,4,-426.99,0,Cards

# High-Impact Analysis

# 1. Region Performance

In [19]:
df.groupby("Region")[["Sales","Profit"]].sum().sort_values(by="Sales", ascending=False)

             Sales    Profit
Region
West     156725.55  20963.89
East     117035.15  19427.94
Central   94118.66  13054.05
South     77549.89   6007.62

# Profit Margin

In [21]:
region = df.groupby("Region")[["Sales","Profit"]].sum()
region["Profit Margin (%)"] = (region["Profit"] / region["Sales"]) * 100
region.sort_values(by="Profit Margin (%)")

             Sales    Profit  Profit Margin (%)
Region
South     77549.89   6007.62           7.746781
West     156725.55  20963.89          13.376179
Central   94118.66  13054.05          13.869779
East     117035.15  19427.94          16.600090

# 2. Category Analysis

In [23]:
df.groupby("Category")[["Sales","Profit"]].sum()

                     Sales    Profit
Category
Furniture        127499.02   3158.28
Office Supplies  161480.66  20618.25
Technology       156449.57  35676.97

# 3. Sub-Category Analysis

In [24]:
df.groupby("Sub-Category")["Profit"].sum().sort_values()

Sub-Category
Tables         -2536.08
Supplies        -913.99
Bookcases       -439.42
Fasteners        145.48
Furnishings      802.37
Envelopes        890.90
Labels           948.89
Art             1072.24
Appliances      3919.65
Binders         4109.52
Storage         4195.01
Machines        4234.93
Chairs          5331.41
Phones          6084.17
Paper           6250.55
Accessories     8456.03
Copiers        16901.84
Name: Profit, dtype: float64

# 4. Top Loss-Making Products

In [26]:
df.sort_values(by="Profit").head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode
5037,684,US-2020-168116,2020-04-11,2020-04-11,Same Day,GT-14635,Grant Thornton,Corporate,United States,Burlington,...,South,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,3009.98,4,-3839.99,0,Online
383,1200,CA-2019-130946,2019-08-04,2019-12-04,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,1088.79,4,-1850.95,0,Online
4702,5321,US-2020-162558,2020-02-10,2020-05-10,First Class,Dp-13240,Dean percer,Home Office,United States,Knoxville,...,South,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,2335.12,7,-1002.78,0,Online
1700,7642,US-2019-157490,2019-06-10,2019-07-10,First Class,LB-16795,Laurel Beltran,Home Office,United States,Pueblo,...,West,TEC-MA-10001695,Technology,Machines,Zebra GK420t Direct Thermal/Thermal Transfer P...,703.71,6,-938.28,0,Online
189,5199,CA-2019-103982,2019-03-03,2019-08-03,Standard Class,AA-10315,Alex Avila,Consumer,United States,Round Rock,...,Central,OFF-SU-10000151,Office Supplies,Supplies,High Speed Automatic Electric Letter Opener,3930.07,3,-786.01,0,Online
5480,1996,US-2020-147221,2020-02-12,2020-04-12,Second Class,JS-16030,Joy Smith,Consumer,United States,Houston,...,Central,OFF-AP-10002534,Office Supplies,Appliances,3.6 Cubic Foot Counter Height Office Refrigerator,334.62,5,-766.01,0,COD
1353,870,CA-2019-158099,2019-03-09,2019-05-09,First Class,PK-18910,Paul Knutson,Home Office,United States,Philadelphia,...,East,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,1141.47,5,-760.98,0,Cards
5483,4498,CA-2020-155075,2020-02-12,2020-09-12,Standard Class,GW-14605,Giulietta Weimer,Consumer,United States,Philadelphia,...,East,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,155.18,4,-462.86,0,COD
3293,8236,CA-2020-102204,2020-01-05,2020-06-05,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Jacksonville,...,South,FUR-TA-10001889,Furniture,Tables,Bush Advantage Collection Racetrack Conference...,952.26,4,-458.15,0,COD
2762,6567,CA-2020-131282,2020-05-02,2020-08-02,Second Class,CB-12025,Cassandra Brandow,Consumer,United States,Waco,...,Central,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,285.99,4,-426.99,0,Cards

# 5. Returns Impact

In [28]:
df.groupby("Returns")["Profit"].mean()

Returns
0    35.258061
1    36.131400
Name: Profit, dtype: float64

## Insights

# “Some regions generate high sales but lower profit margins, indicating inefficiency”
# “Certain sub-categories consistently generate losses”
# “Returned orders significantly reduce profitability”
# “Few products are responsible for major losses”